### ISSUE TITLE
Android kills stream if in background

### ISSUE THREAD

**Issue by Trikolon** [Trikolon/liquidradio#12]
Not sure if this is only an issue on my side. Perhaps there is a way to fix it. Will do some research.

**Comment by ThierryKamber** [comment]
Firefox for Android: Works fine when minimizing the App and also when locking the screen.
Google Chrome for Android: Works fine when minimizing the App and also when locking the screen.

Default browser in MIUI 8: Page does not load correctly (only the development message and gray background visible).
Opera for Android: Page displays normally, but stream doesn't play. ("Stream stalled, check your connection.")

Note that I'm using MIUI 8 with restrictive settings for background Apps enabled and none of the browsers exempted from the setting.

**Comment by Trikolon** [comment]
Thank you very much for the feedback!

**Comment by Trikolon** [comment]
This just happened to me again. When I leave the stream running in the background it works fine for a while but after a longer period of time, let's say 30 minutes, it just kills the application. I guess that is to free ram. (Google Pixel XL)

**Comment by Trikolon** [comment]
I assume that this is happening on OS level and therefore we can't fix it.
