### ISSUE TITLE
connection loss ≠ "stream stalled" notification

### ISSUE THREAD

**Issue by coffeepanda** [Trikolon/liquidradio#22]
When the WiFi connection of my phone breaks off, the device is momentarily without a web connection and the stream stops, no "stream stalled" notification is shown. Upon using 'skip' the message "stream offline" is displayed. When the connection is reestablished only 'skip' resumes the stream, 'play/pause' is without effect.

**Comment by Trikolon** [comment]
I can't reproduce your issue.
What I've tried:
1. Play the stream with internet connection
2. Set network to "offline" in chrome dev tools
3. when the end of  the buffer is reached the "stream stalled" message appears
4. Set network back to "online" in chrome dev tools
5. After a few seconds, the error message "stream offline, check your internet connection" appears, stream is marked offline
6. Click catch-up (skip) button.
7. Stream starts playing again, play/pause and volume works fine.

**Comment by coffeepanda** [comment]
Me neither. It seems to have been a temporary client sided issue.
