### ISSUE TITLE
Visualizer seems not working on Firefox

### ISSUE THREAD

**Issue by mdartic** [Trikolon/liquidradio#32]
Hello, 

Great job in using VueJS + Material !

It seems that visualizer doesn't correctly work on my Firefox (it's ok with Chromium / Chrome) :

![image](https://user-images.githubusercontent.com/2027964/28284647-fd6bc5d2-6b31-11e7-8031-c667f6a06108.png)

I'm using Firefox Nightly 56.0a1 (2017-07-15) (64-bit).

**Comment by mdartic** [comment]
There is an error in the console : 

![image](https://user-images.githubusercontent.com/2027964/28284810-a942e85e-6b32-11e7-927c-90f20d547015.png)

**Comment by mdartic** [comment]
After some debug, it seems the bug occured when you execute the line https://github.com/Trikolon/liquidradio/blob/master/js/app.js#L9, after creating the `audio-visualizer` component.

**Comment by Trikolon** [comment]
Thank you for the contribution!
I haven't tested the application on Firefox yet, but only developed with chrome. I guess we need to look more into browser compatibility.
