### ISSUE TITLE
Working audio streams appear as 'Offline'

### ISSUE THREAD

**Issue by coffeepanda** [Trikolon/liquidradio#34]
Two out of the recently added audio streams ("Rough Tempo" [1] & "DnB Radio" [2]),
both 128kbps mpga, appear as 'Offline' even though their stream source is working fine:
1. https://stream.liquidradio.pro/roughtempo1
2. https://stream.liquidradio.pro/dnbradio1

Pre Proxy Stream Sources:
1. http://37.187.24.165:8000/;stream
2. http://source.dnbradio.com:8000/;stream

**Comment by Trikolon** [comment]
Fixed. There was a config problem in the backend proxy configuration resulting in duplicate headers.
